lojavirtual/carrinho/urls.py
from django.urls import path
from . import views

app_name = 'carrinho' #namespace para diferenciar a url de main
urlpatterns = [
    path('', views.detalhes_carrinho, name='detalhes_carrinho'),
    path('adicionar/<int:id_produto>', views.adicionar_ao_carrinho, name='adicionar_ao_carrinho'),
    path('remover/<int:id_produto>', views.remover_do_carrinho, name='remover_do_carrinho'),
]

lojavirtual/lojavirtual/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from main import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ajuda/', TemplateView.as_view(template_name='ajuda.html'), name='ajuda'),
    path('fale-conosco/', views.ViewFaleConosco.as_view(), name='fale_conosco'),
    #path("", TemplateView.as_view(template_name='index.html'), name='index'), #o django entende a string vazia como um mapeamento para a pagina principal do projeto
    path('carrinho', include('carrinho.urls', namespace='carrinho')),
    path('pedidos/', include('pedidos.urls', namespace='pedidos')),
    path('', include('main.urls', namespace='main')) #urls genéricas
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lojavirtual/main/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

#mapeamento das urls genéricas
app_name='main' #namespace
urlpatterns=[
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('produtos/', views.listar_produtos, name='listar_produtos'),
    path('produtos/<str:slug_categoria>/', views.listar_produtos, name='listar_produtos_por_categoria'),
    #path('produto/<int:id>/<str:slug_produto>/', views.detalhes_produto, name='detalhes_produto'),
    path('produto/<str:slug_produto>/', views.detalhes_produto, name='detalhes_produto'),
    ]

lojavirtual/pedidos/urls.py
from django.urls import path
from . import views

app_name = 'pedidos'
urlpatterns = [
    path('criar/', views.criar_pedido, name='criar_pedido')
]

lojavirtual/carrinho/models.py
from django.db import models

# Create your models here.

lojavirtual/carrinho/forms.py
from django import forms

OPCOES_QUANTIDADE_PRODUTO = []
for i in range(1,50):
    OPCOES_QUANTIDADE_PRODUTO.append((i, str(i))) #valor inteiro como controle, e strings como legenda

class FormAdicionarProdutoAoCarrinho(forms.Form):
    quantidade = forms.TypedChoiceField( #controle drop-down com as quantidades
        choices=OPCOES_QUANTIDADE_PRODUTO, coerce=int #valor convertido para inteiro (propriedade coerce)
    )
    atualizar = forms.BooleanField(required=False, widget=forms.HiddenInput)

lojavirtual/carrinho/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from main.models import Produto
from .carrinho import Carrinho
from .forms import FormAdicionarProdutoAoCarrinho

# Create your views here.
@require_POST #indica que o método só poderá ser do tipo POST
def adicionar_ao_carrinho(request, id_produto):
    carrinho = Carrinho(request) #instancia a classe
    produto = get_object_or_404(Produto, id=id_produto) #esperado a partir do banco de dados
    form = FormAdicionarProdutoAoCarrinho(request.POST)

    if form.is_valid():
        dados = form.cleaned_data
        carrinho.adicionar(produto = produto,
        quantidade = dados['quantidade'],
        atualizar_quantidade=dados['atualizar'])
    return redirect('carrinho:detalhes_carrinho') #redirect redireciona para outra view
    #no redirecionamento os dados são preservados

def remover_do_carrinho(request, id_produto):
    carrinho = Carrinho(request)
    produto = get_object_or_404(Produto, id=id_produto)
    carrinho.remover(produto)
    return redirect('carrinho:detalhes_carrinho')

def detalhes_carrinho(request):
    carrinho = Carrinho(request)
    for item in carrinho:
        item['formulario_adicionar_produto_ao_carrinho'] = FormAdicionarProdutoAoCarrinho(
            initial={'quantidade': item['quantidade'],
                    'atualizar': True}
        )
    return render(request, 'carrinho/detalhes.html', {'carrinho': carrinho})

lojavirtual/templates/carrinho/detalhes.html
{%extends 'base.html'%}
{%load static%}
{%block titulo%}
Seu carrinho de compras
{%endblock%}

{%block conteudo%}
        <table class='table table-striped table-hover'>
            <thead style='background-color: #5AC8FA'>
                <tr>
                    <th>Imagem</th>
                    <th>Produto</th>
                    <th>Quantidade</th>
                    <th>Remover</th>
                    <th>Preço unitário</th>
                    <th>Subtotal</th>
                </tr>
            </thead>
            <tbody>
                {%for item in carrinho%}
                {%with produto=item.produto%}
                <tr>
                    <td><a href='{{produto.get_absolute_url}}'>
                        <img src='{% if produto.imagem %} 
                                {{produto.imagem.url}}
                                {% else %}
                                {% static "img/default.jpg" %}
                                {%endif%}'
                                width='50px' height='50px'>
                                
                    </a></td>
                    <td>{{produto.nome}}</td>
                    <td>{{item.quantidade}}</td>
                    <td>
                        <a href="{% url 'carrinho:remover_do_carrinho' produto.id%}">
                            Remover
                        </a>
                    </td>
                    <td>{{item.preco}}</td>
                    <td>{{item.subtotal}}</td>
                </tr>
                {% endwith %}
                {%endfor%}
                <tr style='background-color: #5AC8FA'>
                    <td><b>Total</b></td>
                    <td colspan='4'></td>
                    <td colspan='num'>
                        <b>R$ {{carrinho.get_total_geral}}</b>
                    </td>
                </tr>
            </tbody>
        </table>
        <p class='text-right'>
            <a href='{% url "main:listar_produtos"%}'
                class='btn btn-primary button-light'>
                Comprar mais produtos
            </a>
            <a href='{% url "pedidos:criar_pedido" %}' class='btn btn-secondary button'>
                Finalizar
            </a>
        </p>
{%endblock%}