lojavirtual/carrinho/urls.py
from django.urls import path
from . import views

app_name = 'carrinho' #namespace para diferenciar a url de main
urlpatterns = [
    path('', views.detalhes_carrinho, name='detalhes_carrinho'),
    path('adicionar/<int:id_produto>', views.adicionar_ao_carrinho, name='adicionar_ao_carrinho'),
    path('remover/<int:id_produto>', views.remover_do_carrinho, name='remover_do_carrinho'),
]

lojavirtual/lojavirtual/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from main import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ajuda/', TemplateView.as_view(template_name='ajuda.html'), name='ajuda'),
    path('fale-conosco/', views.ViewFaleConosco.as_view(), name='fale_conosco'),
    #path("", TemplateView.as_view(template_name='index.html'), name='index'), #o django entende a string vazia como um mapeamento para a pagina principal do projeto
    path('carrinho', include('carrinho.urls', namespace='carrinho')),
    path('pedidos/', include('pedidos.urls', namespace='pedidos')),
    path('', include('main.urls', namespace='main')) #urls genéricas
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lojavirtual/main/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

#mapeamento das urls genéricas
app_name='main' #namespace
urlpatterns=[
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('produtos/', views.listar_produtos, name='listar_produtos'),
    path('produtos/<str:slug_categoria>/', views.listar_produtos, name='listar_produtos_por_categoria'),
    #path('produto/<int:id>/<str:slug_produto>/', views.detalhes_produto, name='detalhes_produto'),
    path('produto/<str:slug_produto>/', views.detalhes_produto, name='detalhes_produto'),
    ]

lojavirtual/templates/snippets/barra_navegacao.html
<nav class='navbar navbar-expand-lg navbar-light bg-primary'>

    <a class='navbar-brand text-light' href="/">
        Loja Virtual
    </a>

    <button class='navbar-toggler' type='button' data-toggle='collapse' data-target='#navbarSupportedContent'>
        <span class='navbar-toggler-icon'></span>
    </button>

    <div class='collapse navbar-collapse' id='navbarSupportedContent'>
        <ul class='navbar-nav mr-auto'>
            <li class='nav-item'>
                <a class='nav-link text-light' href='/admin/main/categoria'>
                    Manutenção de categorias
                </a>
            </li>
            <li class='nav-item'>
                <a class='nav-link text-light' href='/admin/main/produto'>
                    Manutenção de produtos
                </a>
            </li>
            <li class='nav-item'>
                <a class='nav-link text-light' href='/produtos'>
                    COMPRAR
                </a>
            </li>
            <li class='nav-item'>
                <a class='nav-link text-light' href='/fale-conosco'>
                    Fale conosco
                </a>
            </li>
            <li class='nav-item'>
                <a class='nav-link text-light' href='/ajuda'>
                    Ajuda
                </a>
            </li>
            <li class='nav-item'>
                {% with quantidade_itens=carrinho|length %}
                {% if carrinho|length > 0 %}
                Seu carrinho de compras:
                <a class='nav-link text-light'
                    href='{% url "carrinho:detalhes_carrinho" %}'>
                    {{quantidade_itens}} produto{{quantidade_itens|pluralize}} - <!--filtro que coloca 'produto' no plural-->
                    R$ {{carrinho.get_total_geral}}
                </a>
                {%else%}
                Seu carrinho está vazio.
                {%endif%}
                {% endwith %}
            </li>
        </ul>
    </div>
</nav>

lojavirtual/templates/snippets/rodape.html
<div class='navbar fixed-bottom bg-info'>
    Projeto Exemplo do livro "Python e Django: Desenvolvimento Web Moderno e Ágil"
</div>