lojavirtual/carrinho/urls.py
from django.urls import path
from . import views

app_name = 'carrinho' #namespace para diferenciar a url de main
urlpatterns = [
    path('', views.detalhes_carrinho, name='detalhes_carrinho'),
    path('adicionar/<int:id_produto>', views.adicionar_ao_carrinho, name='adicionar_ao_carrinho'),
    path('remover/<int:id_produto>', views.remover_do_carrinho, name='remover_do_carrinho'),
]

lojavirtual/lojavirtual/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from main import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ajuda/', TemplateView.as_view(template_name='ajuda.html'), name='ajuda'),
    path('fale-conosco/', views.ViewFaleConosco.as_view(), name='fale_conosco'),
    #path("", TemplateView.as_view(template_name='index.html'), name='index'), #o django entende a string vazia como um mapeamento para a pagina principal do projeto
    path('carrinho', include('carrinho.urls', namespace='carrinho')),
    path('pedidos/', include('pedidos.urls', namespace='pedidos')),
    path('', include('main.urls', namespace='main')) #urls genéricas
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lojavirtual/main/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

#mapeamento das urls genéricas
app_name='main' #namespace
urlpatterns=[
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('produtos/', views.listar_produtos, name='listar_produtos'),
    path('produtos/<str:slug_categoria>/', views.listar_produtos, name='listar_produtos_por_categoria'),
    #path('produto/<int:id>/<str:slug_produto>/', views.detalhes_produto, name='detalhes_produto'),
    path('produto/<str:slug_produto>/', views.detalhes_produto, name='detalhes_produto'),
    ]

lojavirtual/templates/produto/detalhes.html
{%extends 'base.html'%}
{%load static%}
{%block titulo%}
{%if categoria%}
{{categoria.nome}}
{%else%}
Produtos
{%endif%}
{%endblock%}
{%block conteudo%}
<div class='container'>
    <div class='row' style='margin-top: 6%'>
        <div class='col-sm-8'>
            <div class='loja-item'>
                <div class='row'>
                    <div class='card'>
                        <div class='card-body'>
                        <div class='col-md-6 text-right'>
                            <img src='{% if produto.imagem %}
                                    {{produto.imagem.url}}
                                    {% else %}
                                    {% static "img/default.jpg"%}
                                    {% endif %}'
                                alt='Imagem de {{produto.nome}}'
                                style='height: 170px; width: auto'>
                        </div>
                        <div class='col-md-6'
                            style='padding-left: 20px'>
                            <h3>{{produto.nome}}</h3>
                            <h6>
                                <a href='{{produto.categoria.get_absolute_url}}'>
                                    {{produto.categoria}}
                                </a>
                            </h6>
                            <p class='text-muted'>R$ {{produto.preco}}</p>
                            <form action='{% url "carrinho:adicionar_ao_carrinho" produto.id%}' method='post'>
                                {{form_produto_carrinho}}
                                {%csrf_token%}
                                <input type='submit' value='Adicionar ao carrinho'>
                            </form>
                            <p>{{produto.descricao|safe|linebreaksbr}}</p> <!--tags precedidas por | são filtro de template-->
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}

lojavirtual/templates/produto/listar.html
{%extends 'base.html'%}
{%load static%}
{%block titulo%}

{%if categoria%}
{{categoria.nome}}

{%else%}
Produtos
{%endif%}

{%endblock%}

{%block conteudo%}
<div class='container-fluid'>
    <div class='row' style='margin-top: 6%'>
        <div class='col-sm-i loja-colecao'>
            <div class='loja-item'>
                <div class='row'>
                    {%for produto in lista_produtos%}
                    <div class='col-md-4'>
                        <div class='thumbnail'>
                            <a href='{{produto.get_absolute_url}}'>
                                <img src='{%if produto.imagem%}
                                            {{produto.imagem.url}}
                                            {%else%}
                                            {%static "img/default.jpg"%}
                                            {%endif%}'
                                        alt="Imagem de {{produto.nome}}"
                                        style="height: 130px; width: auto">
                            </a>
                            <div class='caption'>
                                <h3 class='text-center'>
                                    <a href="{{produto.get_absolute_url}}">{{produto.nome}}</a>
                                </h3>
                                <p class="text-center">R$ {{produto.preco}}</p>
                            </div>
                        </div>
                    </div>
                    {%endfor%}
                </div>
            </div>
        </div>
        <div class='col-sm-3 col-sm-offset-1 loja-sidebar'>
            <div class='sidebar-module'>
                <h4>Categorias</h4>
                <ol class='list-unstyled'>
                    <li {%if not categoria%} class='active' {%endif%}>
                        <a href="{%url 'main:listar_produtos'%}">Todos</a>
                    </li>
                    {%for c in lista_categorias%}
                    <li {% if categoria.slug == c.slug %} 
                        class='active' 
                        {%endif%}>
                        <a href="{{c.get_absolute_url}}">{{c.nome}}</a>
                    </li>
                    {%endfor%}
                </ol>
            </div>
        </div>
    </div>
</div>
{%endblock%}