locallibrary/locallibrary/catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    #path('register/', views.register_requests, name='register'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
    path('book/create/', views.BookCreate.as_view(), name='create-book'),
    path('book/<int:pk>/update/', views.BookUpdate.as_view(), name='book_update'),
    path('book/<int:pk>/delete/', views.BookDelete.as_view(), name='book_delete'),
    path('authors/', views.AuthorView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('author/create/', views.AuthorCreate.as_view(), name='author_create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author_update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author_delete'),
    path('borrowed', views.BorrowedListView.as_view(), name='borrowed'),
    path('loan', views.LoanBookCreate.as_view(), name='loan'),
    path('book/copy/', views.CreateBookCopy.as_view(), name='book-copy'),
]

locallibrary/locallibrary/locallibrary/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path
from django.views.generic import RedirectView
from django.conf.urls.static import static #habilita veiculacao de arquivos estaticos
from django.conf import settings 
from catalog import views

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
    path('register/', views.register_requests, name='register'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

locallibrary/locallibrary/catalog/models.py
from django.db import models
from django.db.models.fields import BLANK_CHOICE_DASH
from django.urls import reverse #used to generate URLs by reversing the URL patterns
import uuid #required for unique instances
from django.contrib.auth.models import User
from datetime import date

# Create your models here.
class Genre(models.Model):
    """Model representing a book genre"""
    name = models.CharField(max_length=20, help_text='Enter a book genre (e.g. Science Fiction)')

    def __str__(self) -> str:
        """String representing the Model object"""
        return self.name

    

class Book(models.Model):
    """Model representing a book"""
    title = models.CharField(max_length=50)

    #Foreign Key, a book can only have one author, and multiples authors can have multiples books
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)

    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField('ISBN', max_length=13, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')

    #A genre can contain many books, books can cover many genres
    #Genre is already defined, so we can just specify the object
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')

    def __str__(self):
        """String representing the object"""
        return self.title

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book"""
        return reverse('book-detail', args=[str(self.id)]) #deve ser associada a uma view e template

    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in Admin"""
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = 'Genre'

class BookInstance(models.Model):
    """Representing a specific copy of a book"""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book')
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=30)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On Loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )

    class Meta:
        ordering = ['due_back'] #ordenação
        permissions = (('can_mark_returned' , 'Set book as returned'),) #define as permissões
    
    def __str__(self):
        """String for model object"""
        return f'{self.id} ({self.book.title})'

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

class Author(models.Model):
    """Model representing an author"""
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """Returns the url to access a particular author instance"""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.last_name}, {self.first_name}'

locallibrary/locallibrary/catalog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext as _
import datetime
from django.forms import ModelForm, widgets
from catalog.models import BookInstance, Book, Genre, Author
from crispy_forms.helper import FormHelper

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")
        
        

    def save(self, commit = True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

class RenewBookForm(ModelForm):
    #renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).")
    class Meta:
        model = BookInstance
        fields = ['due_back']
        labels = {'due_back': _('New renewal date')}
        help_texts = {'due_back': _('Enter a date between now and 4 weeks (default = 3)')}

    #Easiest way to validate a field is to modify the clean_<fieldname>() method.
    def clean_due_back(self):
        data = self.cleaned_data['due_back']

        #check if a date is not in the past
        if data < datetime.date.today():
            raise ValidationError(_ ('Invalid date - renewal in the past'))

        #check if a date is in allowed range (4 weeks)
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_ ('Invalid date - renewal more than 4 weeks ahead.'))

        #Always return cleaned data
        return data

class LoanBookForm(ModelForm):
    class Meta:
        model = BookInstance
        fields = ['book', 'imprint', 'due_back', 'borrower', 'status']
        widgets = {
            'imprint': forms.TextInput(attrs={'style': 'width: 50%'},),
            'due_back': forms.TextInput(attrs={'style': 'width: 50%'}),
            'borrower': forms.Select(attrs={"style": 'width: 50%'}),
            'status': forms.Select(attrs={'style': 'width: 50%'})
        }

    book = forms.ModelChoiceField(
        queryset=BookInstance.objects.all().filter(status = 'a'),
        widget=forms.Select(attrs={'style': 'width: 50%'})
    )

class CreateBookCopyForm(ModelForm):
    class Meta:
        model = BookInstance
        fields = ['book', 'imprint', 'due_back', 'borrower', 'status']
        widgets = {
            'imprint': forms.TextInput(attrs={'style': 'width: 50%'}),
            'due_back': forms.TextInput(attrs={'style': 'width: 50%'}),
            'borrower': forms.Select(attrs={"style": 'width: 50%'}),
            'status': forms.Select(attrs={'style': 'width: 50%'})
        }

    book = forms.ModelChoiceField(
        queryset=Book.objects.all(),
        widget=forms.Select(attrs={'style': 'width: 50%'})
    )


class CreateBookForm(ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'author', 'summary', 'isbn', 'genre']
        widgets = {
            'title': forms.TextInput(attrs={'style': 'width: 50%'}),
            'author': forms.TextInput(attrs={'style': 'width: 50%'}),
            'summary': forms.Textarea(attrs={'style': 'width: 50%'}),
            'isbn': forms.TextInput(attrs={'style': 'width: 50%'}),
        }

    author = forms.ModelChoiceField(
        queryset=Author.objects.all(),
        widget=forms.Select(attrs={'style': 'width: 50%'})
    )

    genre = forms.ModelMultipleChoiceField(
        queryset=Genre.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

class CreateAuthorForm(ModelForm):
    class Meta:
        model = Author
        fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
        widgets = {
                'first_name': forms.TextInput(attrs={'style': 'width: 30%'}),
                'last_name': forms.TextInput(attrs={'style': 'width: 30%'}),
                'date_of_birth': forms.TextInput(attrs={'placeholder':'Ex: 1970-01-01', 'style': 'width: 30%'}),
                'date_of_death': forms.TextInput(attrs={'placeholder':'Ex: 1970-01-01', 'style': 'width: 30%'}),
            }

class UpdateAuthorForm(ModelForm):
    class Meta:
        model = Author
        fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
        widgets = {
                'first_name': forms.TextInput(attrs={'style': 'width: 30%'}),
                'last_name': forms.TextInput(attrs={'style': 'width: 30%'}),
                'date_of_birth': forms.TextInput(attrs={'style': 'width: 30%'}),
                'date_of_death': forms.TextInput(attrs={'style': 'width: 30%'}),
            }

class UpdateBookForm(ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'author', 'summary', 'isbn', 'genre']
        widgets = {
            'title': forms.TextInput(attrs={'style': 'width: 50%'}),
            #'author': forms.TextInput(attrs={'style': 'width: 50%'}),
            'summary': forms.Textarea(attrs={'style': 'width: 50%'}),
            'isbn': forms.TextInput(attrs={'style': 'width: 50%'}),
        }

        #labels = {'title': 'titulo', 'author': 'autor'}
    author = forms.ModelChoiceField(
        queryset=Author.objects.all(),
        widget=forms.Select(attrs={'style': 'width: 50%'})
    )

    genre = forms.ModelMultipleChoiceField(
        queryset=Genre.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

locallibrary/locallibrary/catalog/views.py
from django.shortcuts import redirect, render, get_object_or_404
from catalog.models import Book, Author, BookInstance, Genre #importa as classes
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from django.contrib.auth import login
from django.contrib import messages
from .forms import CreateAuthorForm, CreateBookForm, NewUserForm, RenewBookForm, UpdateAuthorForm, UpdateBookForm, LoanBookForm, CreateBookCopyForm

import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import permission_required

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django import forms
from django import http



# Create your views here.
def index(request):
    """View function for home page of site"""

    #Generate counts of some of the main objects
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    #Available books (status = a)
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()

    #the 'all()' is implied by default
    num_authors = Author.objects.count()

    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    num_genres = Genre.objects.all().count()

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_visits': num_visits,
        'num_genres': num_genres,
    }

    #Render the HTML template index.html with data in the context variable
    return render(request, 'index.html', context=context)

def register_requests(request):
    if request.method == 'POST':
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            return redirect("index")
        messages.error(request, "Unsuccessful registration. Invalid information.")
    form = NewUserForm()
    return render(request = request, template_name='register.html', context={'register_form': form})

class BookListView(generic.ListView):
    #Listas genéricas procura por model_name_list.html
    model = Book #view genérica consulta no banco de dados o modelo
    paginate_by = 10

class BookDetailView(generic.DetailView):
    model = Book

class AuthorView(generic.ListView):
    model = Author

class AuthorDetailView(generic.DetailView):
    model = Author

class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """Generic class-based view listing books on loan to current user"""
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')

class BorrowedListView(PermissionRequiredMixin, generic.ListView):
    permission_required = 'catalog.can_mark_returned'
    model = BookInstance
    template_name = 'catalog/borrowed_list.html'

@permission_required('catalog.can_mark_returned')
def renew_book_librarian(request, pk):
    book_instance = get_object_or_404(BookInstance, pk=pk)

    if request.method == 'POST':
        #create a form instance and populate it wit data from the request (binding)
        form = RenewBookForm(request.POST)

        if form.is_valid():
            #process the data as required
            book_instance.due_back = form.cleaned_data['due_back']
            book_instance.save()

            #redirect to an specific page (initial page in this case)
            return HttpResponseRedirect(reverse('borrowed'))
    #if this is a GET or other method, create the default form
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'due_back': proposed_renewal_date})

    context = {
        'form': form,
        'book_instance': book_instance
    }

    return render(request, 'catalog/book_renew_librarian.html', context)

class LoanBookCreate(PermissionRequiredMixin, CreateView):
    permission_required = 'catalog.can_mark_returned'
    model = BookInstance
    form_class = LoanBookForm
    template_name = 'catalog/loan_form.html'
    success_url = reverse_lazy('borrowed')

class CreateBookCopy(PermissionRequiredMixin, CreateView):
    permission_required = 'catalog.can_mark_returned'
    model = BookInstance
    form_class = CreateBookCopyForm
    template_name = 'catalog/book_copy.html'
    success_url = reverse_lazy('books')

class AuthorCreate(PermissionRequiredMixin, CreateView):
    permission_required = 'catalog.can_mark_returned'
    model = Author
    form_class = CreateAuthorForm
    #initial = {'date_of_death': '05/01/2018'}
    template_name='catalog/author_form.html'
    success_url = reverse_lazy('authors')


class AuthorUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = 'catalog.can_mark_returned'
    model = Author
    form_class = UpdateAuthorForm
    #fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']

class AuthorDelete(PermissionRequiredMixin, DeleteView):
    #view Delete espera encontrar um arquivo de confirmação modelname_confirm_delete.html
    permission_required = 'catalog.can_mark_returned'
    model = Author
    success_url = reverse_lazy('authors')

class BookCreate(PermissionRequiredMixin, CreateView):
    permission_required = 'catalog.can_mark_returned'
    model = Book
    form_class = CreateBookForm
    template_name='catalog/book_form.html'
    success_url = reverse_lazy('books')

class BookUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = 'catalog.can_mark_returned'
    model = Book
    form_class = UpdateBookForm
    #fields = ['title', 
     #       'author',
      #      'summary',
       #     'isbn',
        #    'genre',]

class BookDelete(PermissionRequiredMixin, DeleteView):
    permission_required = 'catalog.can_mark_returned'
    model = Book
    success_url = reverse_lazy('books')

    

locallibrary/locallibrary/catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input class='btn btn-primary' type="submit" value="Yes, delete.">
</form>

{% endblock %}

locallibrary/locallibrary/catalog/templates/catalog/author_detail.html
{% extends 'base_generic.html' %}

{% block content %}
<h1>Title: {{author}}</h1>

{% if author.date_of_birth %}
    <p><strong>Birth:</strong> {{author.date_of_birth}}</p>
{% endif %}

{% if author.date_of_death %}
    <p><strong>Died:</strong> {{author.date_of_death}}
{% endif %}

<div style="margin-left:20px;margin-top:20px">
    <h4>Books</h4>

    {% for book in author.book_set.all %}
        <hr>
        <p><a href="{% url 'book-detail' book.pk %}">{{book}}</a>({{book.bookinstance_set.all.count}})</p>
        <p>{{book.summary}}</p>
    {% endfor %}

    {% if user.is_staff %}
        <a class='btn btn-primary' href="{% url 'author_update' author.pk %}">Author Update</a>
        <a class='btn btn-danger' href="{% url 'author_delete' author.pk %}">Author Delete</a>
    {% endif %}
</div>

{% endblock %}

locallibrary/locallibrary/catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}

{% load crispy_forms_tags %}

{% block content %}
  <div class='container-fluid'>
    <h2 class='form-head'>Fill the form below to register or update an Author</h2>
    <hr>
    
    <form action="" method="post">
      {% csrf_token %}
      <table>
      {{ form|crispy }}
      </table>
      <input class='btn btn-primary' type="submit" value="Submit">
    </form>
  </div>

  {% endblock %}

locallibrary/locallibrary/catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
<h1 class='display-4'>Author List</h1>
{% if author_list %}
    <ul class='list-unstyled'>
        {%for author in author_list%}
        <li>
            <a href="{{author.get_absolute_url}}">{{author.last_name}}, {{author.first_name}} ({{author.date_of_birth}} - {% if author.date_of_death %} {{author.date_of_death}} {% endif %})</a>
        </li>
        {% endfor %}
    </ul>
    {%else%}
        <p>There are no authors in the catalog</p>
    {%endif%}

    {% if user.is_staff%}
    <a class='btn btn-primary btn-sm' href="{% url 'author_create' %}">Author Create</a>
    {% endif %}
{% endblock %}

locallibrary/locallibrary/catalog/templates/catalog/book_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Book</h1>

<p>Are you sure you want to delete the book: {{ book }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input class='btn btn-primary' type="submit" value="Yes, delete.">
</form>

{% endblock %}

locallibrary/locallibrary/catalog/templates/catalog/book_copy.html
{% extends "base_generic.html" %}

{% load crispy_forms_tags %}

{% block content %}
  <div class='container-fluid'>
    <h2 class='form-head'>Fill the form below to register a new book's copy</h2>
    <hr>
    
    <form action="" method="post">
      {% csrf_token %}
      <table>
      {{ form|crispy }}
      </table>
      <input class='btn btn-primary' type="submit" value="Submit">
    </form>
  </div>
{% endblock %}

locallibrary/locallibrary/catalog/templates/catalog/book_detail.html
{% extends 'base_generic.html' %}

{% block content %}
<h1>Title: {{book.title}}</h1>

<p><strong>Author:</strong> <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></p>
<p><strong>Summary:</strong> {{book.summary}}</p>
<p><strong>ISBN:</strong> {{book.isbn}}</p>
<!-- <p><strong>Language:</strong>{{book.language}}</p> -->
<p><strong>Genre:</strong>{% for genre in book.genre.all %} {{genre}}{% if not forloop.last %}, {% endif %}{%endfor%}</p>

<div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    <!--criado pelo django para retornar um conjunto de registros BookInstance associados a um Book
        é como se fosse uma pesquisa reversa do lado muitos do relacionamento, constituido por letras
        minúsculas do modelo em que a FK foi declarada-->
    {% for copy in book.bookinstance_set.all %}
        <hr>
        <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{copy.get_status_display}}</p>
        {% if copy.status != 'a' %}
            <p><strong>Due to be returned:</strong> {{copy.due_back}}</p>
        {% endif %}
        <p><strong>Imprint:</strong> {{copy.imprint}}</p>
        <p class='text-muted'><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}

    {% if user.is_staff %}
        <a class='btn btn-primary' href="{% url 'book_update' book.pk %}">Book Update</a>
        <a class='btn btn-danger' href="{% url 'book_delete' book.pk %}">Book Delete</a>
    {% endif %}
</div>

{% endblock %}

locallibrary/locallibrary/catalog/templates/catalog/book_form.html
{% extends "base_generic.html" %}

{% load crispy_forms_tags %}

{% block content %}
  <div class='container-fluid'>

    <h2 class='form-head'>Fill the form below to register or update a Book</h2>
    <hr>

    <form action="" method="post">
      {% csrf_token %}
      <table>
      {{ form|crispy }}
      </table>
      <input class='btn btn-primary' type="submit" value="Submit">
    </form>
  </div>
{% endblock %}

locallibrary/locallibrary/catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
<h1 class='display-4'>Book List</h1>
{% if book_list %}
    <ul class='list-unstyled'>
        {%for book in book_list%}
        <li>
            <a href="{{book.get_absolute_url}}">{{book.title}}</a> ({{book.author}})
        </li>
        {% endfor %}   
        
    </ul>
        {% if user.is_staff %}
            <a class='btn btn-primary btn-sm' href="{% url 'create-book'%}">Register a Book</a>
        {% endif %}
    {%else%}
        <p>There are no books in the library</p>
    {%endif%}
{% endblock %}

locallibrary/locallibrary/catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}

{% load crispy_forms_tags %}

{% block content %}
  <h1>Renew: {{ book_instance.book.title }}</h1>
  <p><strong>Borrower:</strong> {{ book_instance.borrower }}</p>
  <p{% if book_instance.is_overdue %} class="text-danger"{% endif %}><strong>Due date:</strong> {{ book_instance.due_back }}</p>

  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form|crispy }}
    </table>
    <input class='btn btn-primary' type="submit" value="Submit">
  </form>
{% endblock %}

locallibrary/locallibrary/catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1 class='display-4'>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul class='list-unstyled'>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}

locallibrary/locallibrary/catalog/templates/catalog/borrowed_list.html
{% extends "base_generic.html" %}

{% block content %}
{% if user.is_staff %}
    {% if bookinstance_list %}
    <h1 class='display-4'>List of borrowed books</h1>
    <ul class='list-unstyled'>
        {%for instance in bookinstance_list%}
        <li>
            <a href="{{instance.book.get_absolute_url}}">{{instance.book}}</a> ({{instance.due_back}}) - {{instance.borrower}} <a href="{% url 'renew-book-librarian' instance.id%}">Renew</a>
        </li>
        {% endfor %}
    </ul>
    {%else%}
        <p>There are no books in the library</p>
    {%endif%}
{% else %}
    <h2>Access denied.</h2>
{% endif %}
{% endblock %}

locallibrary/locallibrary/catalog/templates/catalog/loan_form.html
{% extends "base_generic.html" %}

{% load crispy_forms_tags %}

{% block content %}
  <div class='container-fluid'>
    <h2 class='form-head'>Fill the form below to loan an available book</h2>
    <hr>
    
    <form action="" method="post">
      {% csrf_token %}
      <table>
        {{ form.book|as_crispy_field }}
        {{ form.imprint|as_crispy_field }}
        {{ form.due_back|as_crispy_field }}
        {{ form.borrower|as_crispy_field }}
        {{ form.status|as_crispy_field }}
      </table>
      <input class='btn btn-primary' type="submit" value="Submit">
    </form>
  </div>
{% endblock %}